### ISSUE TITLE
Reordering portofolio modals 

### ISSUE THREAD

**Issue by rbh007** [digitalcraftsman/hugo-creative-theme#10]
Hello,

I would like to know who to reorder the portofolio photos modals...My website is www.bit-xpert.net
I already tried to modify the modalID ordering, the title , img file and description without success.
I want to oder let's say ... modal ID number 1 to be first image on first row, modalID 2, to be the second image on first row, modalID 3, to be the third  image on first row, modalID 4, to be the first image on second row, modalID 5, to be the second image on second row, modalID 6, to be the third image on second row. Also how can I modify the images order easy ?

You can find the source code files here : https://github.com/rbh007/bit-xpert

Thanks

**Comment by digitalcraftsman** [comment]
The modals are ordered by their filename. Rename the file with modalID 4 so that it appears at the beginning of the file list. Give them a prefix like `1_`, `2_` for the corresponding order in the portfolio.

**Comment by rbh007** [comment]
Thanks

On Wed, Nov 11, 2015 at 12:44 PM, digitalcraftsman <notifications@github.com
