### ISSUE TITLE
Possible support for multilingual site

### ISSUE THREAD

**Issue by tubia** [digitalcraftsman/hugo-creative-theme#12]
Hi,
I'm trying to figure out how to use this theme in order to create a multilingual site.
Actually, using the structure of your `config.toml` I could have different config files basing on language in order to translate label. For example, I could have `config_it-IT.toml`:

``` toml
[params.hero]
        slogan     = "Il tuo bellissimo slogan"
```

and the default in `config_en-GB.toml`.
Do you think this could be a consistent way to operate?
Thank you!

**Comment by digitalcraftsman** [comment]
Hello @tubia,

it seems that this approach is currently the best way to create a multilingual site. I've [asked the same question](https://discuss.gohugo.io/t/best-practices-for-i18n/1276) a few months ago in the forum of Hugo. The final result of this discussion was [this tutorial](https://gohugo.io/tutorials/create-a-multilingual-site/). It also provides some examples of how you can automate some steps with a shell script.

It shouldn't be to complicated and the theme should fit in this workflow since you can change each string in the config file.

**Comment by tubia** [comment]
Hi @digitalcraftsman thank you for the reply, I read before your tutorial (very helpful) but instead to use `/data/translations` I was thinking to use directly `params` in the config file based on the language, so the layout variables could remain the same.

**Comment by digitalcraftsman** [comment]
This shouldn't be a problem. With a quick look that the [command line flags](https://gohugo.io/overview/usage/) we can find the neccessary commands:

Use

```
--config="": config file (default is path/config.yaml|json|toml)
```

to choose the correct config file for your locals and with 

```
--destination="": filesystem path to write files to
```

we can define a different destination for all version of your site.

In combination with a small shell script you should be able to create a little deploy script that generates your website for all locales.

**Comment by tubia** [comment]
Hi @digitalcraftsman 
Thank you for the suggestion! Something like this:

```
hugo build --buildDrafts --verbose --config="config_it.toml" --destination="public/it" --theme="hugo-creative-theme" --port=1313
```

However I still don't know how to manage dynamically a language switcher for the contents.

**Comment by digitalcraftsman** [comment]
Due to the current lack of native i18n support in Hugo you can't do it fully automated. But you might find [this forum post](https://discuss.gohugo.io/t/language-switcher-template-code/1288) useful.

**Comment by tubia** [comment]
Hi @digitalcraftsman,
I think I managed it to work.
I'll explain the method because I think it could be generalized.
First: I start from [this tutorial](https://gohugo.io/tutorials/create-a-multilingual-site/) assuming that you use a different `config.toml` for each language.
I make some assumptions:
1. each language is a subpath of the main URL so `example.com` is the main URL, `example.com/it` the italian version, and so on for the other languages
2. each content translation match with others basing on the slug, that must be the same. So `example.com/it/about` match `example.com/en/about`

For the language switch I use mainly parameters in the `config_XX.toml` file.
Let's start from that:
**config_it.toml**:

``` toml
# Language prefix for building link
    language = "it"
    otherlanguages = ["en", "fr", "es"]
    otherlanguagesdesc = ["inglese", "francese", "spagnolo"]
    basicurl = "http://example.com/"
```

This is, instead, what I write in the `navbar.html` partial:

``` handlebars
<ul class="dropdown-menu">
          {{$langdesc := .Site.Params.otherlanguagesdesc}}
          {{$basicurl := .Site.Params.basicurl}}
          {{$slug := .Slug}}
          {{range $index, $element := .Site.Params.otherlanguages}}
            <li><a href="{{$basicurl}}{{$element}}/{{$slug}}">{{index $langdesc $index}}</a></li>
          {{end}}
</ul>
```

A short explanation: I need to define outside the "for" loop some variables in order to use them. `.slug` is a parameter I defined for each content. What I tried to achieve is the match - the association - between the `otherlanguages` and `otherlanguagesdesc` arrays positions i.e., in another programming language, `otherlanguages[0] = 'en'; otherlanguagesdesc[0] = 'english'`.

I hope my explanation is clear and may be useful to others :)

**Comment by tubia** [comment]
Better than this, you can avoid to use the `basicurl` variable and use instead the standard `baseurl`.
So the template is:

``` handlebars
<ul class="dropdown-menu">
          {{$langdesc := .Site.Params.otherlanguagesdesc}}
          {{$baseurl := .Site.BaseURL}}
          {{$slug := .Slug}}
          {{range $index, $element := .Site.Params.otherlanguages}}
            <li><a href="{{substr $baseurl 0 -3}}{{$element}}/{{$slug}}">{{index $langdesc $index}}</a></li>
          {{end}}
</ul>
```

**Comment by digitalcraftsman** [comment]
Great to see it working. The described approach of solving this problem was explained understandably.

> I hope my explanation is clear and may be useful to others :)

I would suggest you to share your approach with others in the [Hugo forum](https://discuss.gohugo.io/) to reach a wider audience.

**Comment by digitalcraftsman** [comment]
Can this issue be closed or do you have more questions?

**Comment by tubia** [comment]
Hi @digitalcraftsman thank you for the suggestion, I'll do as soon as possible, maybe it could integrate also the multilingual site tutorial in the hugo docs.
I think issue can be closed (we can always add more comments later if a better workflow for multilanguage is found)!
