### ISSUE TITLE
Failed loading icons

### ISSUE THREAD

**Issue by Schokolader** [digitalcraftsman/hugo-creative-theme#19]
My icons aren't loading anymore. I get this message in the development tools of chrome: 
Font from origin 'https://mydomain' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.mydomain.com' is therefore not allowed access. 

When I access my site with mydomain.com it is fine, but when I access my domain with www.mydomain.com then my icons aren't loading. Does someone have any clue what to do here?

**Comment by Schokolader** [comment]
I included a redirect for the webserver. 

```
 https://www.mydomain.com {
   redir https://mydomain.com{uri}
 }
```

Now it's fine but I'm not really satisfied. Is there any other solution?

**Comment by digitalcraftsman** [comment]
The problems seems to be how your server handles https and http connections. Take a look at the corresponding Wikipedia article about [https://en.wikipedia.org/wiki/Cross-origin_resource_sharing](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing). In general it's a security feature that allows the server to define the scope of allowed resources to load from.

While browsing some Go-related Gitter channels I saw you're using Caddy with the Hugo plugin. Maybe the project's maintainers can give you further instructions about it.

**Comment by Schokolader** [comment]
ok thank you! I like this theme very much. Thank you for your work!
