### ISSUE TITLE
Static site wasn't generated

### ISSUE THREAD

**Issue by gigante** [digitalcraftsman/hugo-creative-theme#24]
I miss the feature which generate HTML (and related... js, css, img and fonts) in the `static` folder. Or I miss something in the docs?

**Comment by digitalcraftsman** [comment]
Hello @gigante,

which feature do you exactly mean? Usually you set up your Hugo website and run the `hugo` command in the root of the website. By default the generated HTML will be saved in the `public` directory.

**Comment by gigante** [comment]
I was looking in the `static` folder. My mistake. Thx @digitalcraftsman
