### ISSUE TITLE
Title URL is broken due to https issues

### ISSUE THREAD

**Issue by ascandella** [digitalcraftsman/hugo-creative-theme#25]
See: https://themes.gohugo.io/theme/creative/
Versus: http://themes.gohugo.io/theme/creative/

I'm not actually sure you're doing anything wrong, but the link on this GH project points to HTTPS which renders poorly:

![image](https://cloud.githubusercontent.com/assets/97087/20205665/7e3434b8-a78f-11e6-9066-e3ed2eefdb5b.png)

Compared to the insecure version:

![image](https://cloud.githubusercontent.com/assets/97087/20205673/8b004056-a78f-11e6-8bf9-83bcd0a997da.png)

There's probably a bug upstream somewhere, but in the meantime you may wish to update your URL no `http://` so that people don't land on a broken theme.

Also note that browsing to your theme from the homepage takes you here:

http://themes.gohugo.io/creative/ (inecure)

Even when you start from https://themes.gohugo.io/

**Comment by ascandella** [comment]
Note that this appears to affect others as well:

https://themes.gohugo.io/theme/hugo-theme-wave/

Versus

http://themes.gohugo.io/theme/hugo-theme-wave/

**Comment by digitalcraftsman** [comment]
Hello @sectioneight,

thank you for reporting this issue. Due to security reasons browsers don't like it if a website mixes http and https links to resources. Therefore, some resources are blocked. For more information you can open the developer tools in your browser (with F12) and look at the console tab. However, I just have to fix the way how I link the assets.

**Comment by digitalcraftsman** [comment]
I changed the linking of assets in 98c5e49e04a52db2f21a04fa3bdc3b57b89cefe2. Now I'll update the themes and then we'll see if the changes have the expected effect.

**Comment by ascandella** [comment]
Still seeing a link on the GitHub header to https://themes.gohugo.io/theme/creative/ which isn't serving assets correctly.

**Comment by digitalcraftsman** [comment]
This has been fixed with by hosting the theme site on Netlify.
