### ISSUE TITLE
Parsing error when using Hugo 0.18.x

### ISSUE THREAD

**Issue by luisalvarado** [digitalcraftsman/hugo-creative-theme#30]
I was using Hugo 0.18.1 and it gave me a parsing error (Not localhost but live). I normally use only this theme but with this issue saying something along the lines of /theme/partial/head.html parsing error I could not continue with hugo so had to change it to another theme.

Awesome theme btw. Beautiful indeed.

**Comment by digitalcraftsman** [comment]
Hello @luisalvarado,

thanks for the report and I'm sorry to hear that. I did a fresh clone to test if everything works with a Hugo website. However, I had no issues during that process.

Could you post the error message below? Without further information it's hard to spot the error.

**Comment by luisalvarado** [comment]
Hi digital, after reading your comment I knew it was my mistake so I started digging around. It was a misconfiguration from my end. Thank you for the help friend.

**Comment by digitalcraftsman** [comment]
Does this mean you were able to solve the issue on your own?
