### ISSUE TITLE
Creative Theme is 404 on GoHhugo.io

### ISSUE THREAD

**Issue by MatthewMcD** [digitalcraftsman/hugo-creative-theme#46]
Just thought you'd like to know that the Creative theme is throwing a 404 on the Themes Gallery (https://themes.gohugo.io/theme/creative/)

**Comment by digitalcraftsman** [comment]
Hello Matthew,

we're already aware of this issue. The creative theme isn't the only theme that affected by this issue (see https://github.com/gohugoio/hugoThemes/issues/412). Currently it's under investigation.

**Comment by MatthewMcD** [comment]
Cool,

Happy to help resolve the issues if you need the help. I have been adding a bunch of features to the theme.

Matthew

**Comment by digitalcraftsman** [comment]
The issue has been resolved and all theme demo's should be up and running again.
