### ISSUE TITLE
Do you remember the version number of animate.min.css ?

### ISSUE THREAD

**Issue by scillidan** [digitalcraftsman/hugo-creative-theme#48]
Hi you, ni hao.
Do you remember the version number of `animate.min.css`.
It's in the `hugo-creative-theme/static/css/`

**Comment by anthonyfok** [comment]
@scillidan 你好！

The `animate.min.css` file in this theme was added in June 2015, and by checking the release dates on https://github.com/daneden/animate.css/releases, we can see that the closest non-alpha release is v3.2.6, and indeed the `animate.min.css` matches that in this Creative theme. 
 You may download that version of animate.css from https://github.com/daneden/animate.css/archive/3.2.6.tar.gz or https://github.com/daneden/animate.css/archive/3.2.6.zip

**Comment by scillidan** [comment]
I used cdn. And only in this file, I don't see the version number. You reasoned about it based on the date. Good Job!
And, thank you for your theme!

**Comment by anthonyfok** [comment]
@scillidan I am just an end-user of the theme, not the creator (David Miller) nor the porter to Hugo (digitalcraftsman).

**Comment by scillidan** [comment]
That's right. I forgot it.
