### ISSUE TITLE
toml improvment for example site

### ISSUE THREAD

**Issue by robertsonsamuel** [digitalcraftsman/hugo-creative-theme#5]
You might want to change the 
"theme = "hugo-creative-theme" 
to
theme = "hugo-creative-theme-master"

I didn't understand why my page would not load from following the example. A simple problem, but I can see first time users being confused as if you follow your installation exactly the example site does not appear.

**Comment by digitalcraftsman** [comment]
1. What exactly would be the advantage of the renaming? 
2. I took a look at the README and did the installation process as described. At the end I got the theme running. Could you give further information of how you installed the theme or which step doesn't worked as aspected?

Usually you do the following:

```
$ hugo new site nameOfYourSite
$ cd nameOfYourSite
$ mkdir themes
$ cd themes
$ git clone https://github.com/digitalcraftsman/hugo-creative-theme
$ cd ..
```

Now copy all files and folders that are located in the `exampleSite` directory and move back to the root of your Hugo site. Then paste the all files and merge/replace the existing ones (that were created via `hugo new site nameOfYourSite`).

Finally run `hugo server`

**Comment by robertsonsamuel** [comment]
Ah I see! I downloaded the zip from github. That file is named "hugo-creative-theme-master" 
If you follow the git shell method it works perfectly! Nothing wrong on that part! My mistake!
