### ISSUE TITLE
Adding sections to the theme..

### ISSUE THREAD

**Issue by ghost** [digitalcraftsman/hugo-creative-theme#7]
Hi !

I would like to start by complimenting you on the look and features of this theme. Setting it up was very easy using the params in the config file! Thank you.

My question is most likely a noob question. I am new to Hugo.

I tried linking to another page where I would like to show upcoming events as a list generated automatically. I end up breaking the design by simply adding a link in the href"".

What is the best way to add pages / or anchors with sections to the main page without breaking it?

I appologize if this is not the right place to ask this.

Best
Castillo

**Comment by digitalcraftsman** [comment]
Nice to here that sort of feedback to the theme.

Could you give further information what page you want to link where? Is your page with upcoming events also generated by Hugo?

> What is the best way to add pages / or anchors with sections to the main page without breaking it?

I'm not sure what you mean with "add pages ... to the main page"? The easiest way to create a new section in the main page would be to create a partial like I did with the other sections.

If you have other, **general** questions to Hugo I would like to suggest you to use the [official forum](http://discuss.gohugo.io/). The people over there are usually very helpful with questions.

**Comment by digitalcraftsman** [comment]
Is this issue still active?
