### ISSUE TITLE
Markdown links not parsed params.about

### ISSUE THREAD

**Issue by chris-horner** [digitalcraftsman/hugo-creative-theme#8]
I've set up the most basic of sites following the instructions in this theme's README.md, and I'd like to include some linked text in `params.about` description.

The comments in the example config.toml state that Markdown syntax can be used for most longer texts (and it does seem to work for other sections). Is there a reason why Markdown links aren't parsed in `params.about`?

**Comment by digitalcraftsman** [comment]
Thanks for mentioning this. There is no special reason for the missing markdown support. I just forgot to add it.

**Comment by chris-horner** [comment]
Thanks for fixing this so quickly :D

**Comment by chris-horner** [comment]
Though, this does that the adverse affect of making links invisible against the orange background. Might be worth changing the colour for that section?

**Comment by digitalcraftsman** [comment]
It seems that links aren't intended to be used in that section by the orignial theme. But I've added color with more contrast in c151ee4aca07aa939797df03dd6278d80d0a567b. I hope this works for you.
